[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 2

[[main]]
  name = "About"
  pageRef = "about"
  weight = 3

[[main]]
  name = "Guides"
  pageRef = "guides"
  weight = 4
