backend:
  name: github
  repo: demmylmtd/demmy
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: portfolio
    label: Portfolio
    folder: content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }